variables:
  FEDORA_DEPS: rust cargo git meson ninja-build

pages:
  image: 'registry.fedoraproject.org/fedora:31'
  stage: deploy
  before_script:
    - dnf update -y
    - dnf install -y $FEDORA_DEPS
    - meson --prefix=/usr _build
    - ninja -C _build install
  script:
    - git submodule update --init
    - cargo doc -p libhandy --features=['dox', 'v0_0_12']
    - mv target/doc/ public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
