[options]
girs_dir = "gir-files"
library = "Handy"
version = "0.0"
min_cfg_version = "0.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
# with this option enabled, versions for gir and gir-files saved only to one file to minimize noise
single_version_file = true

external_libraries = [
   "GLib",
   "GObject",
   "Gio",
   "Gtk",
   "Gdk",
   "Pango"
]

generate = ["Handy.CenteringPolicy",
            "Handy.Column",
            "Handy.DialerButton",
            "Handy.Dialer",
            "Handy.DialerCycleButton",
            "Handy.Dialog",
            "Handy.ExpanderRow",
            "Handy.Paginator",
            "Handy.PaginatorIndicatorStyle",
            "Handy.PreferencesGroup",
            "Handy.PreferencesPage",
            "Handy.PreferencesRow",
            "Handy.PreferencesWindow",
            "Handy.SearchBar",
            "Handy.Squeezer",
            "Handy.SqueezerTransitionType",
            "Handy.SwipeGroup",
            "Handy.Swipeable",
            "Handy.TitleBar",
            "Handy.Fold",
            "Handy.LeafletChildTransitionType",
            "Handy.LeafletModeTransitionType",
            "Handy.LeafletTransitionType",
            "Handy.ArrowsDirection",
            "Handy.Arrows",
            "Handy.ActionRow",
            "Handy.ComboRow",
            "Handy.HeaderBar",
            "Handy.HeaderGroup",
            "Handy.ViewSwitcher",
            "Handy.ViewSwitcherBar",
            "Handy.ViewSwitcherPolicy",
            "Handy.Keypad",
            ]

manual = ["Gtk.Bin",
          "Gtk.Box",
          "Gtk.Grid",
          "Gtk.Orientable",
          "Gtk.IconSize",
          "Gtk.ListBoxRow",
          "Gtk.ReliefStyle",
          "Gtk.ScrolledWindow",
          "Gtk.Stack",
          "Gtk.Container",
          "Gtk.Widget",
          "Gtk.HeaderBar",
          "Gtk.Entry",
          "Gtk.Orientation",
          "Gtk.EventBox",
          "Gtk.Dialog",
          "Gtk.Window",
          "Gtk.Button",
          "Gtk.DrawingArea",
          "GObject.Value",
          "Gdk.Event",
          "Gio.ListModel",
          "GLib.String",
          "Pango.EllipsizeMode",
         ]

[[object]]
name = "Handy.ValueObject"
status = "generate"
    [[object.function]]
    name = "dup_string"
    ignore = true
    [[object.function]]
    name = "copy_value"
    ignore = true
    [[object.function]]
    name = "new_take_string"
    ignore = true
    [[object.function]]
    name = "new_string"
    ignore = true
    [[object.property]]
    name = "value"
    ignore = true

[[object]]
name = "Handy.Leaflet"
child_type = "Gtk.Widget"
status = "generate"
    [[object.child_prop]]
    name = "icon-name"
    type = "utf8"
    [[object.child_prop]]
    name = "name"
    type = "utf8"
    [[object.child_prop]]
    name = "needs-attention"
    type = "gboolean"
    [[object.child_prop]]
    name = "position"
    type = "gint"
    [[object.child_prop]]
    name = "title"
    type = "utf8"
