[options]
girs_dir = "gir-files"
library = "Handy"
version = "0.0"
min_cfg_version = "0.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
# with this option enabled, versions for gir and gir-files saved only to one file to minimize noise
single_version_file = true

external_libraries = [
   "GLib",
   "GObject",
   "Gio",
   "Gtk",
   "Gdk",
]

generate = ["Handy.Column",
            "Handy.DialerButton",
            "Handy.Dialer",
            "Handy.DialerCycleButton",
            "Handy.Dialog",
            "Handy.ExpanderRow",
            "Handy.SearchBar",
            "Handy.TitleBar",
            "Handy.Fold",
            "Handy.Leaflet",
            "Handy.LeafletChildTransitionType",
            "Handy.LeafletModeTransitionType",
            "Handy.ArrowsDirection",
            "Handy.Arrows",
            "Handy.ActionRow",
            "Handy.ComboRow",
            "Handy.HeaderGroup",
            ]

manual = ["Gtk.Container",
          "Gtk.Widget",
          "Gtk.HeaderBar",
          "Gtk.Window",
          "Gtk.Dialog",
          "Gtk.Orientation",
          "Gtk.Entry",
          "Gdk.Event",
          "Gio.ListModel",
          "GObject.Value",
         ]

[[object]]
name = "Handy.ValueObject"
status = "generate"
    [[object.function]]
    name = "dup_string"
    ignore = true
    [[object.function]]
    name = "copy_value"
    ignore = true
    [[object.function]]
    name = "new_take_string"
    ignore = true
    [[object.function]]
    name = "new_string"
    ignore = true
    [[object.property]]
    name = "value"
    ignore = true
