// This file was generated by gir (https://github.com/gtk-rs/gir @ 32d1716)
// from gir-files (https://github.com/gtk-rs/gir-files @ 62f3bf0)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%zu\n%zu", sizeof(ABI_TYPE_NAME), alignof(ABI_TYPE_NAME));
    return 0;
}
