// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ArrowsDirection;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::SignalHandlerId;
use glib::signal::connect_raw;
use glib::translate::*;
use glib_sys;
use gtk;
use handy_sys;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib_wrapper! {
    pub struct Arrows(Object<handy_sys::HdyArrows, handy_sys::HdyArrowsClass, ArrowsClass>) @extends gtk::DrawingArea, gtk::Widget;

    match fn {
        get_type => || handy_sys::hdy_arrows_get_type(),
    }
}

impl Arrows {
    #[cfg_attr(feature = "v0_0_12", deprecated)]
    pub fn new() -> Arrows {
        assert_initialized_main_thread!();
        unsafe {
            gtk::Widget::from_glib_none(handy_sys::hdy_arrows_new()).unsafe_cast()
        }
    }
}

#[cfg_attr(feature = "v0_0_12", deprecated)]
impl Default for Arrows {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_ARROWS: Option<&Arrows> = None;

pub trait ArrowsExt: 'static {
    #[cfg_attr(feature = "v0_0_12", deprecated)]
    fn animate(&self);

    #[cfg_attr(feature = "v0_0_12", deprecated)]
    fn get_count(&self) -> u32;

    #[cfg_attr(feature = "v0_0_12", deprecated)]
    fn get_direction(&self) -> ArrowsDirection;

    #[cfg_attr(feature = "v0_0_12", deprecated)]
    fn get_duration(&self) -> u32;

    #[cfg_attr(feature = "v0_0_12", deprecated)]
    fn set_count(&self, count: u32);

    #[cfg_attr(feature = "v0_0_12", deprecated)]
    fn set_direction(&self, direction: ArrowsDirection);

    #[cfg_attr(feature = "v0_0_12", deprecated)]
    fn set_duration(&self, duration: u32);

    fn connect_property_count_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_direction_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    fn connect_property_duration_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<Arrows>> ArrowsExt for O {
    fn animate(&self) {
        unsafe {
            handy_sys::hdy_arrows_animate(self.as_ref().to_glib_none().0);
        }
    }

    fn get_count(&self) -> u32 {
        unsafe {
            handy_sys::hdy_arrows_get_count(self.as_ref().to_glib_none().0)
        }
    }

    fn get_direction(&self) -> ArrowsDirection {
        unsafe {
            from_glib(handy_sys::hdy_arrows_get_direction(self.as_ref().to_glib_none().0))
        }
    }

    fn get_duration(&self) -> u32 {
        unsafe {
            handy_sys::hdy_arrows_get_duration(self.as_ref().to_glib_none().0)
        }
    }

    fn set_count(&self, count: u32) {
        unsafe {
            handy_sys::hdy_arrows_set_count(self.as_ref().to_glib_none().0, count);
        }
    }

    fn set_direction(&self, direction: ArrowsDirection) {
        unsafe {
            handy_sys::hdy_arrows_set_direction(self.as_ref().to_glib_none().0, direction.to_glib());
        }
    }

    fn set_duration(&self, duration: u32) {
        unsafe {
            handy_sys::hdy_arrows_set_duration(self.as_ref().to_glib_none().0, duration);
        }
    }

    fn connect_property_count_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_count_trampoline<P, F: Fn(&P) + 'static>(this: *mut handy_sys::HdyArrows, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer)
            where P: IsA<Arrows>
        {
            let f: &F = &*(f as *const F);
            f(&Arrows::from_glib_borrow(this).unsafe_cast())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::count\0".as_ptr() as *const _,
                Some(transmute(notify_count_trampoline::<Self, F> as usize)), Box_::into_raw(f))
        }
    }

    fn connect_property_direction_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_direction_trampoline<P, F: Fn(&P) + 'static>(this: *mut handy_sys::HdyArrows, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer)
            where P: IsA<Arrows>
        {
            let f: &F = &*(f as *const F);
            f(&Arrows::from_glib_borrow(this).unsafe_cast())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::direction\0".as_ptr() as *const _,
                Some(transmute(notify_direction_trampoline::<Self, F> as usize)), Box_::into_raw(f))
        }
    }

    fn connect_property_duration_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_duration_trampoline<P, F: Fn(&P) + 'static>(this: *mut handy_sys::HdyArrows, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer)
            where P: IsA<Arrows>
        {
            let f: &F = &*(f as *const F);
            f(&Arrows::from_glib_borrow(this).unsafe_cast())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::duration\0".as_ptr() as *const _,
                Some(transmute(notify_duration_trampoline::<Self, F> as usize)), Box_::into_raw(f))
        }
    }
}

impl fmt::Display for Arrows {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Arrows")
    }
}
