// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
use glib::object::Downcast;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use gtk;
use gtk_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct Dialog(Object<ffi::HdyDialog, ffi::HdyDialogClass>): [
        gtk::Dialog => gtk_ffi::GtkDialog,
        gtk::Window => gtk_ffi::GtkWindow,
        gtk::Widget => gtk_ffi::GtkWidget,
    ];

    match fn {
        get_type => || ffi::hdy_dialog_get_type(),
    }
}

impl Dialog {
    #[cfg(any(feature = "v0_0_7", feature = "dox"))]
    pub fn new<P: IsA<gtk::Window>>(parent: &P) -> Dialog {
        assert_initialized_main_thread!();
        unsafe {
            gtk::Widget::from_glib_none(ffi::hdy_dialog_new(parent.to_glib_none().0)).downcast_unchecked()
        }
    }
}
