// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#[cfg(any(feature = "v0_0_10", feature = "dox"))]
use glib::GString;
#[cfg(any(feature = "v0_0_10", feature = "dox"))]
use glib::object::Cast;
use glib::object::IsA;
#[cfg(any(feature = "v0_0_10", feature = "dox"))]
use glib::signal::SignalHandlerId;
#[cfg(any(feature = "v0_0_10", feature = "dox"))]
use glib::signal::connect_raw;
use glib::translate::*;
#[cfg(any(feature = "v0_0_10", feature = "dox"))]
use glib_sys;
use gtk;
use handy_sys;
#[cfg(any(feature = "v0_0_10", feature = "dox"))]
use std::boxed::Box as Box_;
use std::fmt;
#[cfg(any(feature = "v0_0_10", feature = "dox"))]
use std::mem::transmute;

glib_wrapper! {
    pub struct PreferencesRow(Object<handy_sys::HdyPreferencesRow, handy_sys::HdyPreferencesRowClass, PreferencesRowClass>) @extends gtk::ListBoxRow, gtk::Bin, gtk::Container, gtk::Widget;

    match fn {
        get_type => || handy_sys::hdy_preferences_row_get_type(),
    }
}

impl PreferencesRow {
    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    pub fn new() -> PreferencesRow {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(handy_sys::hdy_preferences_row_new())
        }
    }
}

#[cfg(any(feature = "v0_0_10", feature = "dox"))]
impl Default for PreferencesRow {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_PREFERENCES_ROW: Option<&PreferencesRow> = None;

pub trait PreferencesRowExt: 'static {
    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn get_title(&self) -> Option<GString>;

    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn get_use_underline(&self) -> bool;

    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn set_title(&self, title: Option<&str>);

    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn set_use_underline(&self, use_underline: bool);

    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn connect_property_title_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn connect_property_use_underline_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<PreferencesRow>> PreferencesRowExt for O {
    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn get_title(&self) -> Option<GString> {
        unsafe {
            from_glib_none(handy_sys::hdy_preferences_row_get_title(self.as_ref().to_glib_none().0))
        }
    }

    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn get_use_underline(&self) -> bool {
        unsafe {
            from_glib(handy_sys::hdy_preferences_row_get_use_underline(self.as_ref().to_glib_none().0))
        }
    }

    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn set_title(&self, title: Option<&str>) {
        unsafe {
            handy_sys::hdy_preferences_row_set_title(self.as_ref().to_glib_none().0, title.to_glib_none().0);
        }
    }

    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn set_use_underline(&self, use_underline: bool) {
        unsafe {
            handy_sys::hdy_preferences_row_set_use_underline(self.as_ref().to_glib_none().0, use_underline.to_glib());
        }
    }

    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn connect_property_title_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_title_trampoline<P, F: Fn(&P) + 'static>(this: *mut handy_sys::HdyPreferencesRow, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer)
            where P: IsA<PreferencesRow>
        {
            let f: &F = &*(f as *const F);
            f(&PreferencesRow::from_glib_borrow(this).unsafe_cast())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::title\0".as_ptr() as *const _,
                Some(transmute(notify_title_trampoline::<Self, F> as usize)), Box_::into_raw(f))
        }
    }

    #[cfg(any(feature = "v0_0_10", feature = "dox"))]
    fn connect_property_use_underline_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_use_underline_trampoline<P, F: Fn(&P) + 'static>(this: *mut handy_sys::HdyPreferencesRow, _param_spec: glib_sys::gpointer, f: glib_sys::gpointer)
            where P: IsA<PreferencesRow>
        {
            let f: &F = &*(f as *const F);
            f(&PreferencesRow::from_glib_borrow(this).unsafe_cast())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::use-underline\0".as_ptr() as *const _,
                Some(transmute(notify_use_underline_trampoline::<Self, F> as usize)), Box_::into_raw(f))
        }
    }
}

impl fmt::Display for PreferencesRow {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "PreferencesRow")
    }
}
