// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#[cfg(any(feature = "v0_0_12", feature = "dox"))]
use Swipeable;
use glib::object::IsA;
use glib::translate::*;
use handy_sys;
use std::fmt;

glib_wrapper! {
    pub struct SwipeGroup(Object<handy_sys::HdySwipeGroup, handy_sys::HdySwipeGroupClass, SwipeGroupClass>);

    match fn {
        get_type => || handy_sys::hdy_swipe_group_get_type(),
    }
}

impl SwipeGroup {
    #[cfg(any(feature = "v0_0_12", feature = "dox"))]
    pub fn new() -> SwipeGroup {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(handy_sys::hdy_swipe_group_new())
        }
    }
}

#[cfg(any(feature = "v0_0_12", feature = "dox"))]
impl Default for SwipeGroup {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_SWIPE_GROUP: Option<&SwipeGroup> = None;

pub trait SwipeGroupExt: 'static {
    #[cfg(any(feature = "v0_0_12", feature = "dox"))]
    fn add_swipeable<P: IsA<Swipeable>>(&self, swipeable: &P);

    #[cfg(any(feature = "v0_0_12", feature = "dox"))]
    fn get_swipeables(&self) -> Vec<Swipeable>;

    #[cfg(any(feature = "v0_0_12", feature = "dox"))]
    fn remove_swipeable<P: IsA<Swipeable>>(&self, swipeable: &P);
}

impl<O: IsA<SwipeGroup>> SwipeGroupExt for O {
    #[cfg(any(feature = "v0_0_12", feature = "dox"))]
    fn add_swipeable<P: IsA<Swipeable>>(&self, swipeable: &P) {
        unsafe {
            handy_sys::hdy_swipe_group_add_swipeable(self.as_ref().to_glib_none().0, swipeable.as_ref().to_glib_none().0);
        }
    }

    #[cfg(any(feature = "v0_0_12", feature = "dox"))]
    fn get_swipeables(&self) -> Vec<Swipeable> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(handy_sys::hdy_swipe_group_get_swipeables(self.as_ref().to_glib_none().0))
        }
    }

    #[cfg(any(feature = "v0_0_12", feature = "dox"))]
    fn remove_swipeable<P: IsA<Swipeable>>(&self, swipeable: &P) {
        unsafe {
            handy_sys::hdy_swipe_group_remove_swipeable(self.as_ref().to_glib_none().0, swipeable.as_ref().to_glib_none().0);
        }
    }
}

impl fmt::Display for SwipeGroup {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "SwipeGroup")
    }
}
