// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;
#[cfg(any(feature = "v0_0_8", feature = "dox"))]
use glib;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct ValueObject(Object<ffi::HdyValueObject, ffi::HdyValueObjectClass>);

    match fn {
        get_type => || ffi::hdy_value_object_get_type(),
    }
}

impl ValueObject {
    #[cfg(any(feature = "v0_0_8", feature = "dox"))]
    pub fn new(value: &glib::Value) -> ValueObject {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::hdy_value_object_new(value.to_glib_none().0))
        }
    }

    //#[cfg(any(feature = "v0_0_8", feature = "dox"))]
    //pub fn new_collect(type_: glib::types::Type, : /*Unknown conversion*//*Unimplemented*/Fundamental: VarArgs) -> ValueObject {
    //    unsafe { TODO: call ffi::hdy_value_object_new_collect() }
    //}
}

pub trait ValueObjectExt {
    #[cfg(any(feature = "v0_0_8", feature = "dox"))]
    fn get_string(&self) -> Option<String>;

    #[cfg(any(feature = "v0_0_8", feature = "dox"))]
    fn get_value(&self) -> Option<glib::Value>;
}

impl<O: IsA<ValueObject>> ValueObjectExt for O {
    #[cfg(any(feature = "v0_0_8", feature = "dox"))]
    fn get_string(&self) -> Option<String> {
        unsafe {
            from_glib_none(ffi::hdy_value_object_get_string(self.to_glib_none().0))
        }
    }

    #[cfg(any(feature = "v0_0_8", feature = "dox"))]
    fn get_value(&self) -> Option<glib::Value> {
        unsafe {
            from_glib_none(ffi::hdy_value_object_get_value(self.to_glib_none().0))
        }
    }
}
